server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CampanaJF/config-data.git
          clone-on-start: true
          #          username: ${gitUser}
          #          password: ${gitToken}
          default-label: main
